CC=g++ -g -std=c++0x

.PHONY: all clean  build tiempos

all: clean build

clean:
	rm -f problema_2
	rm -f t2
	rm -f generador
	
build:
	$(CC) -o  problema_2  problema_2.cpp
	$(CC) -o  t2  tiempos2.cpp
	$(CC) -o  generador  generadorEntrada.cpp
	
